// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// 
/// To configure Firebase credentials:
/// 1. Copy this file to lib/firebase_options.dart
/// 2. Replace the String.fromEnvironment() values with your actual Firebase credentials
/// 3. Or run the app with --dart-define flags:
///    flutter run --dart-define=FIREBASE_API_KEY=YOUR_KEY \
///                --dart-define=FIREBASE_APP_ID=YOUR_APP_ID \
///                --dart-define=FIREBASE_MESSAGING_SENDER_ID=YOUR_SENDER_ID \
///                --dart-define=FIREBASE_PROJECT_ID=YOUR_PROJECT_ID \
///                --dart-define=FIREBASE_STORAGE_BUCKET=YOUR_BUCKET
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Firebase não configurado para Web. Apenas Android está ativo.',
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      default:
        throw UnsupportedError(
          'Firebase não configurado para esta plataforma. '
          'Apenas Android está ativo.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('FIREBASE_API_KEY'),
    appId: String.fromEnvironment('FIREBASE_APP_ID'),
    messagingSenderId: String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID'),
    projectId: String.fromEnvironment('FIREBASE_PROJECT_ID'),
    storageBucket: String.fromEnvironment('FIREBASE_STORAGE_BUCKET'),
  );
}
